SELECT * FROM pizza_sale.pizza_sales_data; 

alter table pizza_sales_data
rename column ï»¿pizza_id to pizza_id;

# What is the total revenue generated from pizza sales? - Total Revenue

select sum(total_price) as Total_Revenue
from pizza_sales_data;

# What is the total revenue for each order? - Total Revenue by order

select order_id, sum(total_price) as Total_Revenue
from pizza_sales_data
group by order_id;

# What is the formatted total revenue with a fixed number of decimal points?

select format(sum(total_price),1) as Total_Revenue #format coz after decimal point can ajust the no' of values
from pizza_sales_data;

# How many orders have been placed in total?

select count(order_id)
from pizza_sales_data;

# How many distinct orders have been placed?

select count(distinct order_id)
from pizza_sales_data;

# What is the average value of an order?

SELECT format(SUM(total_price)/COUNT(DISTINCT order_id),2) AS Avg_Order_Value
FROM pizza_sales_data;

# Which pizzas are the most popular based on the quantity sold? -Top-Selling pizzas
select pizza_name, SUM(quantity) AS total_quantity_sold
from pizza_sales_data
group by pizza_name
order by total_quantity_sold desc
limit 5;

# What is the total revenue generated by each type of pizza? - Revenue by pizza type 

select pizza_name, format(sum(total_price),2) as 'total_revenue'
from pizza_sales_data
group by pizza_name
order by sum(total_price) desc
limit 5;

# What combinations of pizzas are ordered together in each order? - order combinations
 
SELECT order_id, GROUP_CONCAT(pizza_name) AS pizzas_ordered
FROM pizza_sales_data
GROUP BY order_id;

#Total orders
SELECT COUNT(DISTINCT order_id)
FROM pizza_sales_data;

# What is the average number of pizzas per order? - Average Pizza Per Order

SELECT ROUND((SUM(quantity)/COUNT(DISTINCT order_id)),2) AS Avg_Pizza_Per_Order
FROM pizza_sales_data;

# What is the average value of an order? - Average order value 

select avg(total_price) as 'average_order_value'
from pizza_sales_data;

# On which days were the highest number of orders placed? - High order days

SELECT order_date, COUNT(order_id) AS total_orders
FROM pizza_sales_data
GROUP BY order_date
ORDER BY total_orders DESC
LIMIT 5;

# What is the daily trend for the total number of orders? - daily trend on total orders

SELECT order_date, COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales_data
GROUP BY order_date;

# What is the distribution of orders by pizza size? - Size Distribution

SELECT pizza_size, COUNT(*) AS order_count
FROM pizza_sales_data
GROUP BY pizza_size;

# Total Pizzas Sold by Pizza Category

SELECT pizza_category, 
	SUM(quantity) AS Total_Sale
FROM pizza_sales_data
GROUP BY pizza_category;

# Top 5 Pizzas by Revenue

SELECT pizza_name, 
	SUM(total_price) AS Total_Sale
FROM pizza_sales_data
GROUP BY pizza_name
ORDER BY Total_Sale DESC
LIMIT 5;

# Bottom 5 Pizzas by Revenue

SELECT pizza_name, 
	SUM(total_price) AS Total_Sale
FROM pizza_sales_data
GROUP BY pizza_name
ORDER BY Total_Sale 
LIMIT 5;

# Top 5 'Classic' category pizzas by Total Orders
SELECT pizza_name, 
	COUNT(DISTINCT order_id) AS Total_Order
FROM pizza_sales_data
WHERE pizza_category = 'Classic'
GROUP BY pizza_name
ORDER BY Total_Order DESC
LIMIT 5;


